all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/bootcamp.pem
    ansible_user: ubuntu
    ansible_connection: ssh
    ansible_become: true
    ansible_ssh_common_args: -o StrictHostKeyChecking=no

  children:
    elk-kibana-nodes:
      hosts:
        ec2-54-74-134-81.eu-west-1.compute.amazonaws.com:

    elk-master-nodes:
      hosts:
        ec2-34-252-86-197.eu-west-1.compute.amazonaws.com:
        ec2-54-74-134-81.eu-west-1.compute.amazonaws.com:
        ec2-54-77-204-109.eu-west-1.compute.amazonaws.com:
