- hosts: elk-master-nodes
  roles:
    - role: elastic.elasticsearch
  vars:
    ansible_ssh_private_key_file: "~/.ssh/purbon-ireland-sa.pem"
    ansible_user: "ubuntu"
    es_data_dirs:
      - "/var/lib/elasticsearch"
    es_heap_size: "12g"
    es_config:
      cluster.name: "esprd"
      network.host: 0
      discovery.seed_hosts: "34.253.185.1:9300,52.49.166.219:9300,54.220.124.66:9300"
      http.port: 9200
      node.data: true
      node.master: true
      node.ml: false
      bootstrap.memory_lock: true
      indices.recovery.max_bytes_per_sec: 100mb
