- hosts: elk-kibana-nodes
  become: yes
  tags: kibana
  roles:
    - role: geerlingguy.kibana
  vars:
    kibana_version: "7.x"
    kibana_package: kibana
    kibana_package_state: present
    kibana_server_port: 5601
    kibana_server_host: "0.0.0.0"
    kibana_elasticsearch_url: "http://ec2-54-74-134-81.eu-west-1.compute.amazonaws.com:9200"
