- hosts: elk-master-nodes
  tags: elastic
  roles:
    - role: elastic.elasticsearch
  vars:
    es_data_dirs:
      - "/var/lib/elasticsearch"
    es_heap_size: "12g"
    es_config:
      cluster.name: "esprd"
      network.host: "0.0.0.0"
      discovery.seed_hosts: "ec2-54-74-134-81.eu-west-1.compute.amazonaws.com,ec2-54-77-204-109.eu-west-1.compute.amazonaws.com,ec2-34-252-86-197.eu-west-1.compute.amazonaws.com"
      cluster.initial_master_nodes: "ip-172-32-0-77"
      http.port: 9200
      node.data: true
      node.master: true
      node.ml: false
      node.name: "${HOSTNAME}"
      bootstrap.memory_lock: true
      indices.recovery.max_bytes_per_sec: 100mb
