
CREATE USER 'sven'@'%' IDENTIFIED WITH mysql_native_password BY 'sven-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'sven'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'sven'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'sven'@'%';

CREATE USER 'amy'@'%' IDENTIFIED WITH mysql_native_password BY 'amy-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'amy'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'amy'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'amy'@'%';

CREATE USER 'dennis'@'%' IDENTIFIED WITH mysql_native_password BY 'dennis-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'dennis'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'dennis'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'dennis'@'%';


CREATE USER 'alberto'@'%' IDENTIFIED WITH mysql_native_password BY 'alberto-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'alberto'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'alberto'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'alberto'@'%';

CREATE USER 'marcel'@'%' IDENTIFIED WITH mysql_native_password BY 'marcel-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'marcel'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'marcel'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'marcel'@'%';

CREATE USER 'nakul'@'%' IDENTIFIED WITH mysql_native_password BY 'nakul-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'nakul'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'nakul'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'nakul'@'%';


CREATE USER 'peter'@'%' IDENTIFIED WITH mysql_native_password BY 'peter-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'peter'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'peter'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'peter'@'%';


CREATE USER 'piotr'@'%' IDENTIFIED WITH mysql_native_password BY 'piotr-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'piotr'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'piotr'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'piotr'@'%';

CREATE USER 'rohit'@'%' IDENTIFIED WITH mysql_native_password BY 'rohit-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'rohit'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'rohit'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'rohit'@'%';

CREATE USER 'victor'@'%' IDENTIFIED WITH mysql_native_password BY 'victor-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'victor'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'victor'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'victor'@'%';

CREATE USER 'ray'@'%' IDENTIFIED WITH mysql_native_password BY 'ray-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'ray'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'ray'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'ray'@'%';