
CREATE USER 'sven'@'%' IDENTIFIED WITH mysql_native_password BY 'sven-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'sven'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'sven'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'sven'@'%';

CREATE USER 'adam'@'%' IDENTIFIED WITH mysql_native_password BY 'adam-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'adam'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'adam'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'adam'@'%';

CREATE USER 'lorenc'@'%' IDENTIFIED WITH mysql_native_password BY 'lorenc-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'lorenc'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'lorenc'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'lorenc'@'%';


CREATE USER 'neil'@'%' IDENTIFIED WITH mysql_native_password BY 'neil-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'neil'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'neil'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'neil'@'%';

CREATE USER 'pierpaolo'@'%' IDENTIFIED WITH mysql_native_password BY 'pierpaolo-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'pierpaolo'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'pierpaolo'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'pierpaolo'@'%';

CREATE USER 'victoria'@'%' IDENTIFIED WITH mysql_native_password BY 'victoria-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'victoria'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'victoria'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'victoria'@'%';


CREATE USER 'victor'@'%' IDENTIFIED WITH mysql_native_password BY 'victor-secret'  PASSWORD EXPIRE INTERVAL 30 DAY;

GRANT ALL ON movielens.* TO 'victor'@'%';
GRANT SELECT, EVENT, EXECUTE, LOCK TABLES ON movielens.* TO 'victor'@'%';
GRANT RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'victor'@'%';

