---
- hosts: mysql,postgres
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - domain

- hosts: mysql
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - mysql

- hosts: postgres
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - postgres
